/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUx0UVNOK0lwT0ErNnpxR2VsQWJHeExUcmJYQUp0bENJeUNwa1k2a3VWZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSkFtSEM3NFVoSHlldGpuaFEwWGdLTHhOdHBsWThBMVJHaStxTDYwb0xSUT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpTmtwVWY3MEhoeXppeTluRVVsREhPb3p5ZmxZMml6VjRHL1IwdGZkYWxFPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJicWxTWHZselN5VVZEL1p3cVNHU1hGV05YOGZNZ3NING1nVS9CNmEzVzBRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjhKUXN2OHVSSWxhN3d5MEVqYjkxOCtIMk9VejI1aUNrelpESWN6ZFg0bHc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlpiVnA3bFR0RWgxQ1VuOFJqQkdiUXp3T2VaWXJyVXFERFRQRTlxRmFXbXM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidU5OTWRhWWFnVUJzQkNrNkpVWGhPME9ka3E0M2hDN2RFNU1SeHF3ajZtbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSENHSThabUl6blZlSTRTM1JLblV1Rk8rcTlhZm5rR25jOTk0ZTRlVWFBWT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkpMTk5rMlZtbHRyQ1JpTVJ2eGxYWkVXamJ0bStsMG1BK0k1b3BQSW9QbTZsWUk5Z0s5aXVrVlhxcG1wSnFZYkF2TmRXOWovMEZJZFhtKzVCNlVCNUJBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjcsImFkdlNlY3JldEtleSI6ImtBemlHb0pVQ0JQbnBIRm1RVFFCTlRpcVdmK0pzM0RlVWhId3MwSmlsN0k9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IjdIMVBXSzFDVEU2QVU0eWdVTW1mMlEiLCJwaG9uZUlkIjoiODE2YmQxMzktNTI1MS00MGU4LWExZDEtNzdkMzY0NjI2ZThiIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkxLdDhHS3B6L1lwcWFJQnlERkEvT1paRk9Qbz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpa1ZiMkpKOXhzQldKSFo5N05vTTN3Vlp2TlE9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiWVFKQURWMlQiLCJtZSI6eyJpZCI6IjkyMzA5Nzc5ODE5Nzo4QHMud2hhdHNhcHAubmV0In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNKV2t1Q29RbVpDWXVnWVlBeUFBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJSMEJaQWhncU02RVlHdkNWSm9aMlBEL0VyMVdESWxkT21TNTcxRk9UT0I0PSIsImFjY291bnRTaWduYXR1cmUiOiJQcTczZDQ2czFTVXUzZk5JbFpOSkMrYTRxaUh6SlhJV0dVMmtoaFV4aFRnZ3Y2YVVSU00rL2ZOT3RFWjVPVmVheC9Rdkc0UFpEd3FjOVBiWGlnYnVDUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoibnJsVXgxc1FvMVc4cWZwQk8yWkJHdEg0d2RjY0J3R0ZHbG5jZDRlZUpaQlB2MDFXYXgzZVZhZWErSERrMkMzcDl5QUNMZHpUckUyUTVnQzBlVDQ4Q3c9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5MjMwOTc3OTgxOTc6OEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJVZEFXUUlZS2pPaEdCcndsU2FHZGp3L3hLOVZneUpYVHBrdWU5UlRremdlIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMyNjQyODU0LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUlsWiJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'Akio';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263714757857';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || '𝙰𝙺𝙸𝙾 𝙼𝙳';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
